Desenvolvimento para carregar a tabela de resumo de negocios no periodo
Menighin/cei-crawler pull request #25
Opened 2020-09-30 14:07 UTC by amakens

Prezados, estou enviando essa contribuição, pois a tabela "Resumo de Negócios no período" que tem na página https://cei.b3.com.br/CEI_Responsivo/negociacao-de-ativos.aspx, é muito útil, devido a ter informações de preço médio de compra e venda, sendo também possível pegar informação da sua posição atual com o preço médio.
Realizei o desenvolvimento criando o crawler SummaryStockHistory, criei os testes e atualizei também o README.
Aguardo que a solicitação seja aceita, pois será muito útil para mim e outros da comunidade.

2020-10-01 01:28 UTC, Menighin requested changes
Fiz alguns comentários visando a manutenabilidade do código.
Além disso faltam testes para o código novo, você consegue fazer?

Sobre os testes falharem, o Travis não disponibiliza as variaveis ambiente para Pull Requests por motivo de segurança, quando a gente mergear que a gente vai ver se vai passar a build e consertar o que precisar.

Abraços

2020-10-01 01:28 UTC, Menighin commented on README.md
> +		"period":"31/08/2020",
Favor transformar o campo `period` em um `Date` do javascript para manter a consistencia da API.

2020-10-01 01:28 UTC, Menighin commented on README.md
> +#### getSummaryStockHistoryOptions()
Precisa desse método? Ele não seria o mesmo do `StockHistoryCrawler.getStockHistoryOptions`?

2020-10-01 01:28 UTC, Menighin commented on src/lib/SummaryStockHistoryCrawler.js
> +const puppeteer = require('puppeteer');
Toda a lógica de seleção de conta e filtragem desse crawler é a mesma do `StockHistoryCrawler`.
Por serem crawlers que estão lidando com a mesma página, o correto é que reaproveitemos os códigos para maior manutenabilidade.
Poderia fazer a função `getSummaryStockHistory` no `StockHistoryCrawler`, extrair a lógica de navegação/filtro para uma função e reaproveitá-la tanto no crawler que pega as negociacoes quanto nesse cara novo 👍

2020-10-01 14:18 UTC, amakens commented on README.md
> +		"period":"31/08/2020",
Esse eu não posso colocar como Date, porque o campo pode vir assim: "31/08/2020 à 15/09/2020", quando tem a compra e venda.

2020-10-01 14:21 UTC, amakens commented
Pronto realizei todas as alterações e fiz os testes, com exceção do campo "period", pois a informação do CEI B3 pode vir "31/08/2020 à 15/09/2020", quando tem uma operação fechada("compra" e "venda")

2020-10-02 21:58 UTC, Menighin commented
Obrigado pelo PR @amakens 
Ainda tem alguns probleminhas de formatação mas eu mergeio, do uma arrumada e subo.
Até amanhã devo conseguir lançar a versao! Valeu! 👍

2020-10-02 21:58 UTC, merged