Including support for fetching IPO data from CEI.
Menighin/cei-crawler pull request #36
Opened 2021-02-25 14:41 UTC by hugow182

Adding IPOCrawler class for retrieving IPO transactions from a range of dates.

2021-02-25 16:35 UTC, Menighin reviewed
Poderia por favor atualizar a documentação também com as novas funcionalidades disponibilizadas?

2021-02-25 16:35 UTC, Menighin commented on src/lib/CeiCrawler.js
> +    // /**
Algum motivo pra esse código comentado?

2021-02-26 10:17 UTC, hugow182 commented on src/lib/CeiCrawler.js
> +    // /**
Não.

Somente esqueci de tirar esse trecho.

A ideia era disponibilizar dois métodos:
1 - Que recebesse com input uma data única para pegar as transações de ofertas públicas.
2 - Que recebesse um intervalo de dataspara pegar as  transações de ofertas públicas.

Eu acabei desistindo da primeira pq o segundo método pode receber duas datas iguais e fazer a mesma coisa que o método um.

Mas enfim, eu apenas esqueci de remover o comentário.

2021-02-27 14:43 UTC, felipesdias requested changes
Acho que ficou faltando apenas os testes, seria legal manter a cobertura.

2021-02-28 20:47 UTC, Menighin commented
Vou mergear e assim que possivel eu implemento os testes e subo a lib.
Se vc conseguir fazer os testes antes é só abrir outro PR.
Muito obrigado pela contribuição!

2021-02-28 20:47 UTC, merged

2021-02-28 23:51 UTC, hugow182 commented
Assim que der eu tento implementar o testes.

Eu que agradeço pela iniciativa de vocês.

Abs,
Hugo Bruno.

On Sun, Feb 28, 2021, 5:47 PM João Menighin <notifications@github.com>
wrote:

> Merged #36 <https://github.com/Menighin/cei-crawler/pull/36> into master.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Menighin/cei-crawler/pull/36#event-4386518278>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARP4V32OTKUS5QFZSK2NTNTTBKTW3ANCNFSM4YGUARXA>
> .
>

2021-03-02 19:30 UTC, Menighin commented
Opa eu cheguei a implementar uns testes basicos hugow182.
Como a gente nao usa mock nos testes, nao consegui testar muito, dado que eu mesmo nunca entrei em IPO e minha conta do CEI que é usada nos testes haha
Se quiser incrementar algo fica a vontade! Abs!